# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"

	config.vm.define "main" do |main|
		main.vm.network :private_network, ip: "192.168.33.10"
	end
 
	config.vm.network "forwarded_port", guest: 2375, host: 2375
	config.vm.network "forwarded_port", guest: 4243, host: 4243
	config.vm.network "forwarded_port", guest: 8090, host: 8090
	config.vm.network "forwarded_port", guest: 1080, host: 1080




	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.cpus = 2
		vb.memory = "2048"
	end

	config.vm.provision "shell" do |shell|
	shell.path = "docker.sh"
	end
end