Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-20.04"
	
	config.vm.define "main" do |main|
		main.vm.hostname = 'jenkins'
	end
	
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.cpus = 2
		vb.memory = "2048"
	end

	config.vm.provision "shell" do |shell|
		shell.path = "jenkins.sh"
	end
 end
 