version: '3.8'

services:
  wildfly:
    image: jboss/wildfly:21.0.0.Final.Postgres
    build: ./wildfly
    networks:
      - wildfly
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      DB_HOST: wildfly-postgres
      DB_NAME: st2eedb
      DB_USER: adm
      DB_PASS: adm
      DS_NAME: Project
      JNDI_NAME: java:jboss/datasources/Project
    volumes:
      - ./target/M1-JEE-Project-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/Project.war
    depends_on:
      - wildfly-postgres

  wildfly-postgres:
    image: postgres:13
    networks:
      - wildfly
    restart: always
    volumes:
        - ./database/wildfly-postgres/data:/var/lib/postgresql/data
        - ./database/scripts/JEE_db.sql:/docker-entrypoint-initdb.d/1.JEE_db.sql
        - ./database/scripts/Populate.sql:/docker-entrypoint-initdb.d/2.Populate.sql
    environment:
        POSTGRES_DB: st2eedb
        POSTGRES_USER: adm
        POSTGRES_PASSWORD: adm
        
networks:
    wildfly: